### ISSUE TITLE
Unable to access customer entry from cart data

### ISSUE THREAD

**Issue by jacksleight** [duncanmcclean/simple-commerce#463] opened 2021-09-08 11:51 UTC
### Description

The cart data contains a `customer` key, which contains a Value object. Once the customer's name and email address have been submitted this object's raw value is the customer ID, however when you try to fetch the actual value you get `null` instead of the customer entry.

I need the customer entry because I want people to be able to go back to previous steps during checkout, so I need to output the previously submitted name and email values in that step. Address data is fine as that's available in the cart data. (Perhaps customer name and email should be in the cart data as well?)

### Steps to reproduce

I'm not doing this in antlers, so this example is just using plain PHP.

1. Add something to the basket
2. Proceed to checkout, going as far as the step where you submit the name and email address
3. Get the cart data
4. Call `$cart['customer']->raw()`, the ID of the customer entry is returned
5. Call `$cart['customer']->value()`, and `null` is returned

If you fetch the entry via Statamic's Entry facade it works fine:

```php
Statamic\Facades\Entry::find($cart['customer']->raw()) // Returns the customer entry, not null
```

That's what I'm currently doing as a workaround.

### Environment

Statamic 3.2.2 Pro
Laravel 8.57.0
PHP 7.4.21
doublethreedigital/simple-commerce 2.3.24

**Comment by duncanmcclean** [comment] 2021-09-08 12:28
Sorry if I'm misunderstanding you - where are you running `$cart['customer']->raw()`?

**Comment by jacksleight** [comment] 2021-09-08 13:06
This is probably a bit unusual because I'm using blade, so I can't use any of the antlers tags to fetch the cart data etc.

Instead it's all just plain PHP. Here's a simplified example of what I'm currently doing:

```blade
@php
$cart = resolve(CartDriver::class)->getOrMakeCart()->toAugmentedArray();
$customer = Entry::find($cart['customer']->raw())->toAugmentedArray();
// $customer = $cart['customer']->value()->toAugmentedArray(); // doesn't work because value() returns null
@endphp

<input name="name" value="{{ $customer['name'] ?? null }}" />
```

Perhaps there's another/better way to do it?

**Comment by duncanmcclean** [comment] 2021-09-08 13:14
Hmm, it should just be the same as any other entry field - since that's all it is (an entry fieldtype)

**Comment by duncanmcclean** [comment] 2021-09-08 13:19
Ohh, you're going through the cart driver thing... I'm not quite sure why that doesn't work, I'd need to take a closer look.

FYI: You should also be able to grab the customer like so:

```ph
$customer = resolve(CartDriver::class)->getOrMakeCart()->customer()->toAugmentedArray();
```

**Comment by jacksleight** [comment] 2021-09-08 13:32
Ah perfect, thanks I'll do it like that for now.

**Comment by duncanmcclean** [comment] 2021-09-09 17:18
Hmm, seems to be working fine for me.. 🤔 

```php
$cart = resolve(CartDriver::class)->getOrMakeCart()->toAugmentedArray();

dd($cart['customer']->value());
```

![image](https://user-images.githubusercontent.com/19637309/132732468-4ef4fe4b-0855-4397-b144-ad352a0df0c2.png)

**Comment by jacksleight** [comment] 2021-09-10 08:35
That's odd... Curiously I have another issue that might be related. When I view the orders list in the control panel the customer name's aren't displayed:

![Screenshot 2021-09-10 at 09 33 10](https://user-images.githubusercontent.com/126740/132825341-badec5c1-fdc2-4262-8349-88e56af0bdd4.png)

But they do appear when you view an order:

![Screenshot 2021-09-10 at 09 33 18](https://user-images.githubusercontent.com/126740/132825388-3e36e024-9d39-4380-831a-dfc668b52123.png)

Could this be related? Perhaps I have something misconfigured somehow?

**Comment by duncanmcclean** [comment] 2021-09-10 08:48
Hmm strange. What does the customer field in your order blueprint look like?

**Comment by jacksleight** [comment] 2021-09-10 08:50
```yaml
      -
        handle: customer
        field:
          max_items: 1
          mode: default
          collections:
            - customers
          type: entries
          listable: hidden
          display: Customer
          width: 50
```

**Comment by duncanmcclean** [comment] 2021-09-10 08:57
Hmm, that looks fine. What does your Simple Commerce config file look like?

**Comment by jacksleight** [comment] 2021-09-10 08:59
https://gist.github.com/jacksleight/6fd05b1922b6e06de33f749c1d9b6737

**Comment by duncanmcclean** [comment] 2021-09-10 09:24
Huh, that all looks okay as well. Not sure what else could be causing it 🤔 

I'll see if I can reproduce it again (tonight) with a fresh site based off the starter kit.

**Comment by jacksleight** [comment] 2021-09-10 13:43
Appear to have the same issue(s) in a fresh install with the SC starter:

![Screenshot 2021-09-10 at 14 35 20](https://user-images.githubusercontent.com/126740/132862155-8489c29b-5618-4c63-8160-4d6cffeb57f0.png)

Attempting to echo the customer name in the shipping view displays nothing:

```
{{ sc:cart:update redirect="/checkout/payment" }}
    {{ customer:name }}
    {{ customer:email }}
{{ /sc:cart:update }}
```

And if I convert that to a blade template and add this:

```blade
@php
$cart = resolve(DoubleThreeDigital\SimpleCommerce\Contracts\CartDriver::class)->getOrMakeCart()->toAugmentedArray();
dump($cart['customer']);
dump($cart['customer']->value());
@endphp
```

I get:

![Screenshot 2021-09-10 at 14 42 35](https://user-images.githubusercontent.com/126740/132862717-972b4818-395b-4018-b18d-1738e7e710cb.png)

**Comment by duncanmcclean** [comment] 2021-09-10 14:06
Hmm, I'll take a look this evening. Very strange!

**Comment by duncanmcclean** [comment] 2021-09-10 15:43
Ahh, I can reproduce now. Looking into it.

**Comment by duncanmcclean** [comment] 2021-09-10 16:14
Found & fixed in [v2.3.25](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.3.25) - essentially the customer entries were not published and the augmentation only works when the entry is in a published state.

Not sure about the CP index issue, that's still there but I don't think that's a Simple Commerce issue - possibly a Statamic one.

**Closed as completed by duncanmcclean** 2021-09-10 16:14 UTC
Labels: bug

**Comment by jacksleight** [comment] 2021-09-13 09:35
Brilliant, thanks.

Yeah, it looks like entries columns in the CP listings are blank if the linked entry is not published.

By the looks of it [this change](https://github.com/statamic/cms/pull/3544) caused this, and [this bug](https://github.com/statamic/cms/issues/3918) is kind of related.

**Comment by jacksleight** [comment] 2021-09-13 10:00
Filed a bug: https://github.com/statamic/cms/issues/4251
